### ISSUE TITLE
docs: README Endpoints are inverted

### ISSUE THREAD

**Issue by bogdaaamn** [encoredev/example-app-diary#2]
Currently the README reads

> ## Endpoints
> 
> Create new diary entry:
> 
> ```bash
> curl -X GET "http://localhost:4000/logbook/entries/2022-09-08" | jq
> ```
> 
> ```json
> {
>   "Entries": [
>     {
>       "Id": 1,
>       "Time": "2022-09-08T16:25:21.409544Z",
>       "Text": "I cooked fried eggs this morning. I forgot how much I loved them!"
>     }
>   ]
> }
> ```
> 
> Listing all my entries for a specific date:
> 
> ```bash
> curl -X POST --data '{"Text":"I cooked fried eggs this morning. I forgot how much I loved them!"}' "http://localhost:4000/logbook/entries"
> ```
> 
> ```json
> {
>   "Id": 6,
>   "Time": "2022-09-08T16:25:21.409544Z",
>   "Text": "I cooked fried eggs this morning. I forgot how much I loved them!"
> }
> ```

Whilst I believe you meant the other way around 

> ## Endpoints
> 
> Listing all my entries for a specific date:
> 
> ```bash
> curl -X GET "http://localhost:4000/logbook/entries/2022-09-08" | jq
> ```
> 
> ```json
> {
>   "Entries": [
>     {
>       "Id": 1,
>       "Time": "2022-09-08T16:25:21.409544Z",
>       "Text": "I cooked fried eggs this morning. I forgot how much I loved them!"
>     }
>   ]
> }
> ```
> 
> Create new diary entry:
> 
> ```bash
> curl -X POST --data '{"Text":"I cooked fried eggs this morning. I forgot how much I loved them!"}' "http://localhost:4000/logbook/entries"
> ```
> 
> ```json
> {
>   "Id": 6,
>   "Time": "2022-09-08T16:25:21.409544Z",
>   "Text": "I cooked fried eggs this morning. I forgot how much I loved them!"
> }
> ```

**Comment by bih** [comment]
Ah, of course! Good catch. Want to pop this in a PR and I can merge it? :)

**Comment by bogdaaamn** [comment]
Here we go #3 🤘🏼
